from typing import List, TypedDict, Annotated, Optional
import operator
from langchain_core.messages import BaseMessage

class GraphState(TypedDict):
    """
    Represents the state of our multi-agent graph.
    """
    # The original user query
    query: str
    
    # A list of messages in the conversation, using operator.add to append new messages
    messages: Annotated[List[BaseMessage], operator.add]
    
    # --- Planning & Reflection Fields ---
    # The current set of sub-queries generated by the Planner
    plan: List[dict] # Each dict contains 'query' and 'source'
    
    # Number of times the planning has been rejected by the Validator
    retry_count: int
    
    # Feedback from the Validator to the Planner
    planning_feedback: str
    # ------------------------------------

    # Stores the output from the SE Process Agent (context/answers)
    process_output: List[str]
    
    # The final answer produced by the Synthesizer
    final_answer: str
    
    # Control variable to decide the next node in the graph
    next_step: Optional[str]
    
    # Summary of the conversation so far (Long-term context)
    summary: str

    # The intent of the current user query (e.g., 'process', 'general')
    current_intent: str
